from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from uuid import UUID

from .models import AuditEvent, PasswordResetToken, Permission, Role, Session, User


class UserRepositoryPort:
    async def create_user(self, user: User) -> User: ...

    async def get_by_id(self, user_id: UUID) -> User | None: ...

    async def get_by_email_or_username(self, identifier: str) -> User | None: ...

    async def update_user(self, user: User) -> User: ...

    async def list_roles(self, user_id: UUID) -> Sequence[Role]: ...

    async def list_permissions(self, role_ids: Sequence[UUID]) -> Sequence[Permission]: ...


class SessionRepositoryPort:
    async def create_session(self, session: Session) -> Session: ...

    async def get_active_session(self, session_id: UUID) -> Session | None: ...

    async def revoke_session(self, session_id: UUID, revoked_at: datetime) -> Session | None: ...

    async def update_session(self, session: Session) -> Session: ...


class PasswordResetRepositoryPort:
    async def create_reset_token(self, token: PasswordResetToken) -> PasswordResetToken: ...

    async def get_active_token(self, token_hash: str) -> PasswordResetToken | None: ...

    async def mark_used(self, token_id: UUID, used_at: datetime) -> PasswordResetToken | None: ...


class AuditRepositoryPort:
    async def record_event(self, event: AuditEvent) -> AuditEvent: ...
