from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from app.domain.models import TaxAuditEvent, TaxBracket, TaxCalculation, TaxDeduction, TaxExemption, TaxRuleBundle, TaxRuleComponent
from app.domain.events import TaxAuditEventPayload


class TaxRuleBundleRepositoryProtocol(Protocol):
    async def create_bundle(self, bundle: TaxRuleBundle) -> TaxRuleBundle: ...
    async def update_bundle(self, bundle: TaxRuleBundle) -> TaxRuleBundle: ...
    async def get_bundle_by_id(self, bundle_id: UUID) -> TaxRuleBundle | None: ...
    async def list_bundles(self) -> Sequence[TaxRuleBundle]: ...
    async def find_applicable_bundle(self, jurisdiction_code: str, tax_category_code: str, taxpayer_class_code: str, assessment_date) -> TaxRuleBundle | None: ...


class TaxBracketRepositoryProtocol(Protocol):
    async def create_bracket(self, bracket: TaxBracket) -> TaxBracket: ...
    async def list_brackets_for_bundle(self, tax_rule_bundle_id: UUID) -> Sequence[TaxBracket]: ...


class TaxDeductionRepositoryProtocol(Protocol):
    async def create_deduction(self, deduction: TaxDeduction) -> TaxDeduction: ...
    async def list_deductions_for_bundle(self, tax_rule_bundle_id: UUID) -> Sequence[TaxDeduction]: ...


class TaxExemptionRepositoryProtocol(Protocol):
    async def create_exemption(self, exemption: TaxExemption) -> TaxExemption: ...
    async def list_exemptions_for_bundle(self, tax_rule_bundle_id: UUID) -> Sequence[TaxExemption]: ...


class TaxCalculationRepositoryProtocol(Protocol):
    async def create_calculation(self, calculation: TaxCalculation) -> TaxCalculation: ...
    async def get_calculation_by_id(self, calculation_id: UUID) -> TaxCalculation | None: ...
    async def list_calculations_for_subject(self, taxpayer_subject: str) -> Sequence[TaxCalculation]: ...


class TaxAuditRepositoryProtocol(Protocol):
    async def record_event(self, event: TaxAuditEventPayload) -> TaxAuditEvent: ...
    async def list_events_for_resource(self, resource_type: str, resource_id: str) -> Sequence[TaxAuditEvent]: ...
