from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.events import AuditEvent
from app.domain.models import (
    WorkflowApplication,
    WorkflowApplicationEvent,
    WorkflowApprovalChain,
    WorkflowApprovalStep,
    WorkflowDefinition,
    WorkflowEscalationRule,
    WorkflowState,
    WorkflowTransition,
)


class WorkflowDefinitionRepositoryPort(Protocol):
    async def create_definition(self, definition: WorkflowDefinition) -> WorkflowDefinition: ...
    async def update_definition(self, definition: WorkflowDefinition) -> WorkflowDefinition: ...
    async def get_definition_by_id(self, definition_id: UUID) -> WorkflowDefinition | None: ...
    async def get_definition_by_code_version(self, code: str, version: str) -> WorkflowDefinition | None: ...
    async def list_definitions(self) -> Sequence[WorkflowDefinition]: ...


class WorkflowStateRepositoryPort(Protocol):
    async def create_state(self, state: WorkflowState) -> WorkflowState: ...
    async def update_state(self, state: WorkflowState) -> WorkflowState: ...
    async def get_state_by_id(self, state_id: UUID) -> WorkflowState | None: ...
    async def list_states_for_definition(self, definition_id: UUID) -> Sequence[WorkflowState]: ...


class WorkflowTransitionRepositoryPort(Protocol):
    async def create_transition(self, transition: WorkflowTransition) -> WorkflowTransition: ...
    async def get_transition_by_id(self, transition_id: UUID) -> WorkflowTransition | None: ...
    async def get_transition(self, definition_id: UUID, from_state_id: UUID, action: str) -> WorkflowTransition | None: ...
    async def list_transitions_for_definition(self, definition_id: UUID) -> Sequence[WorkflowTransition]: ...


class WorkflowApprovalChainRepositoryPort(Protocol):
    async def create_chain(self, chain: WorkflowApprovalChain) -> WorkflowApprovalChain: ...
    async def get_chain_by_id(self, chain_id: UUID) -> WorkflowApprovalChain | None: ...
    async def get_active_chain_for_state(self, definition_id: UUID, source_state_id: UUID) -> WorkflowApprovalChain | None: ...
    async def list_chains_for_definition(self, definition_id: UUID) -> Sequence[WorkflowApprovalChain]: ...


class WorkflowApprovalStepRepositoryPort(Protocol):
    async def create_step(self, step: WorkflowApprovalStep) -> WorkflowApprovalStep: ...
    async def list_steps_for_chain(self, chain_id: UUID) -> Sequence[WorkflowApprovalStep]: ...


class WorkflowEscalationRuleRepositoryPort(Protocol):
    async def create_rule(self, rule: WorkflowEscalationRule) -> WorkflowEscalationRule: ...
    async def get_active_rule_for_state(self, definition_id: UUID, source_state_id: UUID) -> WorkflowEscalationRule | None: ...
    async def list_rules_for_definition(self, definition_id: UUID) -> Sequence[WorkflowEscalationRule]: ...


class WorkflowApplicationRepositoryPort(Protocol):
    async def create_application(self, application: WorkflowApplication) -> WorkflowApplication: ...
    async def update_application(self, application: WorkflowApplication) -> WorkflowApplication: ...
    async def get_application_by_id(self, application_id: UUID) -> WorkflowApplication | None: ...
    async def list_applications(self) -> Sequence[WorkflowApplication]: ...
    async def list_applications_for_subject(self, applicant_subject: str) -> Sequence[WorkflowApplication]: ...


class WorkflowApplicationEventRepositoryPort(Protocol):
    async def create_event(self, event: WorkflowApplicationEvent) -> WorkflowApplicationEvent: ...


class AuditRepositoryPort(Protocol):
    async def record_event(self, event: AuditEvent) -> AuditEvent: ...
