from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.domain.events import AuditEvent
from app.domain.models import CitizenProfile, CitizenshipRecord, DocumentMetadata


class CitizenProfileRepositoryPort(Protocol):
    async def create_profile(self, profile: CitizenProfile) -> CitizenProfile: ...
    async def update_profile(self, profile: CitizenProfile) -> CitizenProfile: ...
    async def get_profile_by_id(self, profile_id: UUID) -> CitizenProfile | None: ...
    async def get_profile_by_identity_subject(self, identity_subject: str) -> CitizenProfile | None: ...
    async def list_profiles(self) -> Sequence[CitizenProfile]: ...


class CitizenshipRecordRepositoryPort(Protocol):
    async def create_record(self, record: CitizenshipRecord) -> CitizenshipRecord: ...
    async def update_record(self, record: CitizenshipRecord) -> CitizenshipRecord: ...
    async def get_record_by_id(self, record_id: UUID) -> CitizenshipRecord | None: ...
    async def list_records_for_profile(self, profile_id: UUID) -> Sequence[CitizenshipRecord]: ...
    async def revoke_record(self, record_id: UUID, revoked_at: datetime) -> CitizenshipRecord | None: ...


class DocumentMetadataRepositoryPort(Protocol):
    async def create_document(self, document: DocumentMetadata) -> DocumentMetadata: ...
    async def update_document(self, document: DocumentMetadata) -> DocumentMetadata: ...
    async def get_document_by_id(self, document_id: UUID) -> DocumentMetadata | None: ...
    async def list_documents_for_profile(self, profile_id: UUID) -> Sequence[DocumentMetadata]: ...
    async def delete_document(self, document_id: UUID, deleted_at: datetime) -> DocumentMetadata | None: ...


class AuditRepositoryPort(Protocol):
    async def record_event(self, event: AuditEvent) -> AuditEvent: ...