from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol
from uuid import UUID

from app.domain.events import AuditEvent, ApplicationHistoryEventCreate
from app.domain.models import Application, ApplicationDocument, ApplicationHistoryEvent


class ApplicationRepositoryProtocol(Protocol):
    async def create_application(self, application: Application) -> Application: ...
    async def update_application(self, application: Application) -> Application: ...
    async def get_application_by_id(self, application_id: UUID) -> Application | None: ...
    async def get_application_by_reference(self, reference_number: str) -> Application | None: ...
    async def list_applications_for_subject(self, applicant_subject: str) -> Sequence[Application]: ...


class ApplicationDocumentRepositoryProtocol(Protocol):
    async def create_document(self, document: ApplicationDocument) -> ApplicationDocument: ...
    async def get_document_by_id(self, document_id: UUID) -> ApplicationDocument | None: ...
    async def list_documents_for_application(self, application_id: UUID) -> Sequence[ApplicationDocument]: ...


class ApplicationHistoryRepositoryProtocol(Protocol):
    async def create_event(self, event: ApplicationHistoryEventCreate, application_id: UUID) -> ApplicationHistoryEvent: ...
    async def list_events_for_application(self, application_id: UUID) -> Sequence[ApplicationHistoryEvent]: ...


class AuditRepositoryProtocol(Protocol):
    async def record_event(self, event: AuditEvent) -> AuditEvent: ...


class WorkflowClientProtocol(Protocol):
    async def submit_application(self, *, definition_code: str, definition_version: str, entity_type: str, entity_id: str, title: str, payload: dict[str, object], application_metadata: dict[str, object], applicant_subject: str) -> dict[str, object]: ...
    async def get_application(self, workflow_application_id: str) -> dict[str, object]: ...
