from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from typing import Protocol
from uuid import UUID

from app.domain.models import Notification, NotificationDeliveryAttempt, NotificationEvent, NotificationQueueItem, NotificationTemplate


@dataclass(slots=True)
class NotificationDeliveryResult:
    success: bool
    provider_message_id: str | None = None
    error_code: str | None = None
    error_message: str | None = None
    response_payload: dict[str, object] | None = None


class NotificationProviderProtocol(Protocol):
    provider_name: str

    async def deliver(self, notification: Notification, template: NotificationTemplate, queue_item: NotificationQueueItem, attempt_no: int) -> NotificationDeliveryResult: ...


class NotificationTemplateRepositoryProtocol(Protocol):
    async def create_template(self, template: NotificationTemplate) -> NotificationTemplate: ...
    async def get_template_by_id(self, template_id: UUID) -> NotificationTemplate | None: ...
    async def get_template_by_code(self, template_code: str, version_number: int | None = None) -> NotificationTemplate | None: ...
    async def list_templates(self) -> Sequence[NotificationTemplate]: ...


class NotificationRepositoryProtocol(Protocol):
    async def create_notification(self, notification: Notification) -> Notification: ...
    async def get_notification_by_id(self, notification_id: UUID) -> Notification | None: ...
    async def list_notifications_for_subject(self, recipient_subject: str) -> Sequence[Notification]: ...
    async def count_notifications_for_subject(self, recipient_subject: str) -> int: ...
    async def count_unread_notifications_for_subject(self, recipient_subject: str) -> int: ...


class NotificationQueueRepositoryProtocol(Protocol):
    async def create_queue_item(self, queue_item: NotificationQueueItem) -> NotificationQueueItem: ...
    async def list_due_queue_items(self, limit: int) -> Sequence[NotificationQueueItem]: ...
    async def get_queue_items_for_notification(self, notification_id: UUID) -> Sequence[NotificationQueueItem]: ...


class NotificationDeliveryRepositoryProtocol(Protocol):
    async def create_attempt(self, attempt: NotificationDeliveryAttempt) -> NotificationDeliveryAttempt: ...
    async def list_attempts_for_notification(self, notification_id: UUID) -> Sequence[NotificationDeliveryAttempt]: ...


class NotificationEventRepositoryProtocol(Protocol):
    async def create_event(self, event: NotificationEvent) -> NotificationEvent: ...
    async def list_events_for_notification(self, notification_id: UUID) -> Sequence[NotificationEvent]: ...
